port=0

# only for logging, thus optional
log-dhcp

# change this to your subnet, below is the default Fritz!Box subnet
dhcp-range=192.168.178.0,proxy

dhcp-match=set:ipxe,175

# replace 192.168.178.93 with the IP of the server running this container
dhcp-option=option:server-ip-address,192.168.178.93

pxe-service=tag:!ipxe,x86PC,    "Boot BIOS PXE",  netboot.xyz.kpxe, 192.168.178.93
pxe-service=tag:!ipxe,X86-64_EFI,"Boot UEFI PXE", netboot.xyz.efi,  192.168.178.93
pxe-service=tag:!ipxe,BC_EFI,   "Boot UEFI PXE",  netboot.xyz.efi,  192.168.178.93

pxe-service=tag:ipxe,x86PC,    "iPXE Catch", netboot.xyz.kpxe, 192.168.178.93
pxe-service=tag:ipxe,X86-64_EFI,"iPXE Catch", netboot.xyz.efi,  192.168.178.93
pxe-service=tag:ipxe,BC_EFI,   "iPXE Catch", netboot.xyz.efi,  192.168.178.93